export { default as TopBar } from "./topbar/TopBar"
export { default as Navbar } from "./navbar/Navbar"
export { default as FirstSection } from "./firstSection/FirstSection"
export { default as QuienesSomos } from "./quienesSomos/QuienesSomos"
export { FlooringSections } from "./flooringSection/FlooringSections"
export { default as ProjectSection } from "./projectSection/ProjectSection"
export { default as OpinionesCarousel } from "./opinionesSection/OpinionesCarousel"
export { default as ContactForm } from "./contactForm/ContactForm"
export { default as Footer } from "./footer/Footer"
